import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { ModeToggle } from "@/components/toggle-theme";
// import { Provider } from "@/components/theme-provider";
// import { Toaster } from "sonner";
import { cn } from "@/lib/utils";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sandeep's Portfolio",
  description: "Generated by sandeep.dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(inter.className, "h-full", "bg-slate-600", "overflow", "text-white")}>
          {children}
        {/* <ModeToggle />
        <Provider>
          <Toaster richColors position="bottom-center" />
        </Provider> */}
      </body>
    </html>
  );
}
